### ISSUE TITLE
传了一会儿报错停止

### ISSUE THREAD

**Issue by Left024** [gaowanliang/OneDriveUploader#2]
如图
<img src="https://chevereto.left.pink/images/2021/04/19/2021-04-19_13-05-17.png" style="zoom: 50%;" />

**Comment by gaowanliang** [comment]
我知道这个问题，你先在启动参数后面加 `-l zh-CN` 来解决这个问题，我稍后解决英文版的这个问题

**Comment by Left024** [comment]
> 我知道这个问题，你先在启动参数后面加 `-l zh-CN` 来解决这个问题，我稍后解决英文版的这个问题

好的，谢谢
