### ISSUE TITLE
linux输入url后报错

### ISSUE THREAD

**Issue by Mapzle** [gaowanliang/OneDriveUploader#22]
系统是Debian 10, 64 bits
报错为
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main/graph/net/http.getAccessToken(0x7ffd8fc407cc, 0x56, 0x0, 0x7ffd8fc40826, 0x5, 0x0, 0x0)
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:115 +0xc41
main/graph/net/http.NewPassCheck(0x7ffd8fc407cc, 0x56, 0x0, 0x7ffd8fc40826, 0x5, 0x0, 0x0)
        D:/program_data/go/LightUploader/graph/net/http/OAuth2.go:42 +0x92
main.ApplyForNewPass(0x7ffd8fc407cc, 0x56, 0x0, 0x3a, 0x0)
        D:/program_data/go/LightUploader/main.go:32 +0x101
main.main()
        D:/program_data/go/LightUploader/main.go:403 +0xc0d

**Comment by gaowanliang** [comment]
是在申请json阶段吗，可能是选错了账户类型

**Comment by Mapzle** [comment]
> 是在申请json阶段吗，可能是选错了账户类型
感谢解答。还真是，很抱歉犯了低级错误。
最后还有其他的问题就另开吧，本贴结束
